name: check-submodules

on:
  pull_request:
    paths:
      - '**'

jobs:
  check-submodules-on-main:
    if: '! github.event.pull_request.draft'

    runs-on: ubuntu-latest

    environment: check-submodules

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.SUBMODULE_ACCESS }}

    - name: Check submodules
      run: ./scripts/check-submodule main
